### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Yriokiri** [giovanni-bozzano/betonquest-gui-plugin#1]
Hi is possible to make this compatible with Betonquest 2.0.0?

**Comment by Bossbirdyman51** [comment]
+1

**Comment by Yriokiri** [comment]
i made it compatible but idk a lot java so i jsut can't make the compass work

**Comment by DomDL** [comment]
I updated the plugin to the latest DEV release 2.0.0-406-DEV. It should work for this version and for future ones until they change something core-related.
